-- pgcdc embeddings table for embedding adapter
-- Generated by: pgcdc init --table {{.Table}} --adapter embedding
-- Dimension: {{.Dimension}} (text-embedding-3-small=1536, text-embedding-3-large=3072)
--
-- Requires the pgvector extension. Install it with:
--   CREATE EXTENSION IF NOT EXISTS vector;
-- Or use the pgvector/pgvector Docker image which includes it.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS {{.Table}} (
    source_id    TEXT PRIMARY KEY,
    source_table TEXT NOT NULL,
    content      TEXT NOT NULL,
    embedding    vector({{.Dimension}}),
    event_id     TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- HNSW index for approximate nearest-neighbor search (no training required,
-- unlike IVFFlat). Cosine distance is standard for text embeddings.
CREATE INDEX IF NOT EXISTS idx_{{.Table}}_embedding
    ON {{.Table}} USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_{{.Table}}_source_table
    ON {{.Table}} (source_table);
