-- pgpipe events table for pg_table adapter
-- Generated by: pgpipe init --table {{.Table}} --adapter pg_table

CREATE TABLE IF NOT EXISTS {{.Table}} (
    id TEXT PRIMARY KEY,
    channel TEXT NOT NULL,
    operation TEXT NOT NULL,
    payload JSONB NOT NULL,
    source TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_{{.Table}}_channel ON {{.Table}} (channel);
CREATE INDEX IF NOT EXISTS idx_{{.Table}}_created_at ON {{.Table}} (created_at);
