version: "2"

formatters:
  enable:
    - gofumpt

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - prealloc
    - unused
    - ineffassign
    - bodyclose
    - nolintlint
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
