version: 2

builds:
  - id: pgcdc
    main: ./cmd/pgcdc
    binary: pgcdc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/florinutz/pgcdc/cmd.Version={{.Version}}

  - id: pgcdc-slim
    main: ./cmd/pgcdc
    binary: pgcdc-slim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - no_kafka
      - no_grpc
      - no_iceberg
      - no_nats
      - no_redis
      - no_plugins
      - no_kafkaserver
      - no_views
    ldflags:
      - -s -w -X github.com/florinutz/pgcdc/cmd.Version={{.Version}}-slim

archives:
  - id: pgcdc
    builds:
      - pgcdc
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: pgcdc-slim
    builds:
      - pgcdc-slim
    format: tar.gz
    name_template: "{{ .ProjectName }}-slim_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: pgcdc
    ids:
      - pgcdc
    repository:
      owner: florinutz
      name: homebrew-tap
    homepage: "https://github.com/florinutz/pgcdc"
    description: "Stream database changes to webhooks, SSE, Kafka, and more"
    license: "MIT"
    install: |
      bin.install "pgcdc"
    test: |
      system "#{bin}/pgcdc", "version"

dockers:
  - image_templates:
      - "ghcr.io/florinutz/pgcdc:{{ .Version }}-amd64"
    ids:
      - pgcdc
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    goarch: amd64
  - image_templates:
      - "ghcr.io/florinutz/pgcdc:{{ .Version }}-arm64"
    ids:
      - pgcdc
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: Dockerfile
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/florinutz/pgcdc:{{ .Version }}"
    image_templates:
      - "ghcr.io/florinutz/pgcdc:{{ .Version }}-amd64"
      - "ghcr.io/florinutz/pgcdc:{{ .Version }}-arm64"
  - name_template: "ghcr.io/florinutz/pgcdc:latest"
    image_templates:
      - "ghcr.io/florinutz/pgcdc:{{ .Version }}-amd64"
      - "ghcr.io/florinutz/pgcdc:{{ .Version }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
