// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: adapter/grpc/proto/pgcdc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []string               `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_adapter_grpc_proto_pgcdc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_grpc_proto_pgcdc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_adapter_grpc_proto_pgcdc_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Traceparent   string                 `protobuf:"bytes,7,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_adapter_grpc_proto_pgcdc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_grpc_proto_pgcdc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_adapter_grpc_proto_pgcdc_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Event) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

var File_adapter_grpc_proto_pgcdc_proto protoreflect.FileDescriptor

const file_adapter_grpc_proto_pgcdc_proto_rawDesc = "" +
	"\n" +
	"\x1eadapter/grpc/proto/pgcdc.proto\x12\x05pgcdc\".\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\tR\bchannels\"\xc2\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12 \n" +
	"\vtraceparent\x18\a \x01(\tR\vtraceparent2C\n" +
	"\vEventStream\x124\n" +
	"\tSubscribe\x12\x17.pgcdc.SubscribeRequest\x1a\f.pgcdc.Event0\x01B/Z-github.com/florinutz/pgcdc/adapter/grpc/protob\x06proto3"

var (
	file_adapter_grpc_proto_pgcdc_proto_rawDescOnce sync.Once
	file_adapter_grpc_proto_pgcdc_proto_rawDescData []byte
)

func file_adapter_grpc_proto_pgcdc_proto_rawDescGZIP() []byte {
	file_adapter_grpc_proto_pgcdc_proto_rawDescOnce.Do(func() {
		file_adapter_grpc_proto_pgcdc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapter_grpc_proto_pgcdc_proto_rawDesc), len(file_adapter_grpc_proto_pgcdc_proto_rawDesc)))
	})
	return file_adapter_grpc_proto_pgcdc_proto_rawDescData
}

var file_adapter_grpc_proto_pgcdc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adapter_grpc_proto_pgcdc_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: pgcdc.SubscribeRequest
	(*Event)(nil),            // 1: pgcdc.Event
}
var file_adapter_grpc_proto_pgcdc_proto_depIdxs = []int32{
	0, // 0: pgcdc.EventStream.Subscribe:input_type -> pgcdc.SubscribeRequest
	1, // 1: pgcdc.EventStream.Subscribe:output_type -> pgcdc.Event
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adapter_grpc_proto_pgcdc_proto_init() }
func file_adapter_grpc_proto_pgcdc_proto_init() {
	if File_adapter_grpc_proto_pgcdc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapter_grpc_proto_pgcdc_proto_rawDesc), len(file_adapter_grpc_proto_pgcdc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapter_grpc_proto_pgcdc_proto_goTypes,
		DependencyIndexes: file_adapter_grpc_proto_pgcdc_proto_depIdxs,
		MessageInfos:      file_adapter_grpc_proto_pgcdc_proto_msgTypes,
	}.Build()
	File_adapter_grpc_proto_pgcdc_proto = out.File
	file_adapter_grpc_proto_pgcdc_proto_goTypes = nil
	file_adapter_grpc_proto_pgcdc_proto_depIdxs = nil
}
