// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: plugin/proto/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel         string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Operation       string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Source          string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAtUnixNs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ns,json=createdAtUnixNs,proto3" json:"created_at_unix_ns,omitempty"`
	Transaction     *TransactionInfo       `protobuf:"bytes,7,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_plugin_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_plugin_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Event) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetCreatedAtUnixNs() int64 {
	if x != nil {
		return x.CreatedAtUnixNs
	}
	return 0
}

func (x *Event) GetTransaction() *TransactionInfo {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type TransactionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Xid              uint32                 `protobuf:"varint,1,opt,name=xid,proto3" json:"xid,omitempty"`
	CommitTimeUnixNs int64                  `protobuf:"varint,2,opt,name=commit_time_unix_ns,json=commitTimeUnixNs,proto3" json:"commit_time_unix_ns,omitempty"`
	Seq              int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_plugin_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInfo) GetXid() uint32 {
	if x != nil {
		return x.Xid
	}
	return 0
}

func (x *TransactionInfo) GetCommitTimeUnixNs() int64 {
	if x != nil {
		return x.CommitTimeUnixNs
	}
	return 0
}

func (x *TransactionInfo) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_plugin_proto_event_proto protoreflect.FileDescriptor

const file_plugin_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/proto/event.proto\x12\x0fpgcdc.plugin.v1\"\xf2\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12+\n" +
	"\x12created_at_unix_ns\x18\x06 \x01(\x03R\x0fcreatedAtUnixNs\x12B\n" +
	"\vtransaction\x18\a \x01(\v2 .pgcdc.plugin.v1.TransactionInfoR\vtransaction\"d\n" +
	"\x0fTransactionInfo\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\rR\x03xid\x12-\n" +
	"\x13commit_time_unix_ns\x18\x02 \x01(\x03R\x10commitTimeUnixNs\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seqB)Z'github.com/florinutz/pgcdc/plugin/protob\x06proto3"

var (
	file_plugin_proto_event_proto_rawDescOnce sync.Once
	file_plugin_proto_event_proto_rawDescData []byte
)

func file_plugin_proto_event_proto_rawDescGZIP() []byte {
	file_plugin_proto_event_proto_rawDescOnce.Do(func() {
		file_plugin_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_event_proto_rawDesc), len(file_plugin_proto_event_proto_rawDesc)))
	})
	return file_plugin_proto_event_proto_rawDescData
}

var file_plugin_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_proto_event_proto_goTypes = []any{
	(*Event)(nil),           // 0: pgcdc.plugin.v1.Event
	(*TransactionInfo)(nil), // 1: pgcdc.plugin.v1.TransactionInfo
}
var file_plugin_proto_event_proto_depIdxs = []int32{
	1, // 0: pgcdc.plugin.v1.Event.transaction:type_name -> pgcdc.plugin.v1.TransactionInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_proto_event_proto_init() }
func file_plugin_proto_event_proto_init() {
	if File_plugin_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_event_proto_rawDesc), len(file_plugin_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_proto_event_proto_goTypes,
		DependencyIndexes: file_plugin_proto_event_proto_depIdxs,
		MessageInfos:      file_plugin_proto_event_proto_msgTypes,
	}.Build()
	File_plugin_proto_event_proto = out.File
	file_plugin_proto_event_proto_goTypes = nil
	file_plugin_proto_event_proto_depIdxs = nil
}
